from typing import Dict, Optional
import zipfile
import xml.etree.ElementTree as ET


def get_metadata_generic(filename: str, keys: Dict[str, Optional[str | int]]) -> dict:
    """Extracts generic metadata from a EBSD/EDS zip file generated by EDAX TEAM.

    Args:
        filename (str): path to the EDAX zip file from which to extract the metadata.

    Returns:
        metadata (dict): metadata corresponding to openBIS object type(s) "EBSD_EXP_DATA", "EBSD-EDS_DATA", or "EDS_DATA":
    """
    XML_METADATA_FILENAME = "sourceFilesList.xml"

    zip_fname = str(filename).replace("\\", "/").split("/")[-1]

    if not str(zip_fname).lower().endswith(".zip"):
        raise ValueError(
            f"Error when parsing {zip_fname} using AMETEK/EDAX parser. ZIP file is expected."
        )
    metadata = dict.fromkeys(keys)

    with zipfile.ZipFile(filename, "r") as zf:

        extensions = set()
        for name in zf.namelist():
            if "." in name.replace("\\", "/").split("/")[-1]:
                ext = name.split(".")[-1]
                extensions.add("." + ext.lower())
        # if {".spc", ".spd", ".osc"}.issubset(extensions):
        #     datatype = "EBSD+EDS"
        # elif ".spd" in extensions or ".spc" in extensions:
        #     datatype = "EDS"
        # elif ".osc" in extensions:
        #     datatype = "EBSD"
        # else:
        #     datatype = "INDETERMINED"

        for name in zf.namelist():
            if name.endswith(XML_METADATA_FILENAME):
                source_file_name = name
                break
        else:
            source_file_name = ""
        if source_file_name == "":
            raise ValueError(
                f"Expected: {XML_METADATA_FILENAME} in {zip_fname} produced by AMETEK/EDAX software"
            )
        project_name_list = []
        sample_name_list = []
        area_name_list = []

        with zf.open(source_file_name) as f:
            tree = ET.parse(f)
            root = tree.getroot()
            for child in root:
                file_data = child.text.split("\\")
                if len(file_data) == 11:
                    project_name_list.append(file_data[7])
                    sample_name_list.append(file_data[8])
                    area_name_list.append(file_data[9])
        project_name_list = list(set(project_name_list))
        sample_name_list = list(set(sample_name_list))
        area_name_list = list(set(area_name_list))

        # openBIS does not allow for list, vector, etc., so we only return first element

        metadata["PROJECT_NAME"] = project_name_list[0] if project_name_list else None
        metadata["NUM_SAMPLES"] = len(sample_name_list)
        metadata["NUM_AREAS"] = len(area_name_list)
        # assert len(sample_name_list) == 1, f"One sample per zip !!! Found {len(sample_name_list)} samples."

        metadata["SAMPLE_NAME"] = ",".join(sample_name_list)
        metadata["AREA_NAME"] = ",".join(area_name_list)
    # ############################## Sanity Check #############################

    # Check if the keys match the schema

    set_a = set(metadata.keys())
    set_b = set(keys)
    problematic_keys = set_a.symmetric_difference(set_b)
    assert set_a == set_b, "Problematic keys: %s" % problematic_keys

    return metadata
