# These are the keys of the dictionary that are used in the definiton of
# the datatype in openBIS
# i.e. the automatic metadata extraction script needs to fill these keys
# and pass them on to openBIS when registering a file of type "CRYS-STRUCT_DATA"

keys_StructDict = [
    "DATE",
    "FILE_SOURCE",
    "LAMMPS_UNIT_STYLE",
    "FILE_SOURCE",
    "ELEMENT_1",
    "ELEMENT_1_AT_PERCENT",
    "ELEMENT_1_NUMBER",
    "ELEMENT_2",
    "ELEMENT_2_AT_PERCENT",
    "ELEMENT_2_NUMBER",
    "ELEMENT_3",
    "ELEMENT_3_AT_PERCENT",
    "ELEMENT_3_NUMBER",
    "ELEMENT_4",
    "ELEMENT_4_AT_PERCENT",
    "ELEMENT_4_NUMBER",
    "ELEMENT_5",
    "ELEMENT_5_AT_PERCENT",
    "ELEMENT_5_NUMBER",
    "ELEMENT_6",
    "ELEMENT_6_AT_PERCENT",
    "ELEMENT_6_NUMBER",
    "ELEMENT_7",
    "ELEMENT_7_AT_PERCENT",
    "ELEMENT_7_NUMBER",
    "ELEMENT_8",
    "ELEMENT_8_AT_PERCENT",
    "ELEMENT_8_NUMBER",
    "NUMBER_OF_ATOMS",
    "NUMBER_OF_ATOM_TYPES",
    "LIST_OF_ATOM_TYPES",
    "NUMBER_OF_SPECIES",
    "LIST_OF_SPECIES",
    "BOX_LENGTH_A",
    "BOX_LENGTH_B",
    "BOX_LENGTH_C",
    "ANGLE_ALPHA",
    "ANGLE_BETA",
    "ANGLE_GAMMA",
    "SPACE_GROUP",
]
